# fly.toml app configuration file generated for sentinel-backend on 2023-10-20T14:08:56+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sentinel-backend"
primary_region = "syd"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
